### PR TITLE
Fix EXC_BAD_ACCESS in FLEXNetworkObserver

### PR DESCRIPTION
**Pull request by ahmedgomaa27**
the crash happened after I used FLEX and Firestore in my app, the root cause for it is trying to set error in Orig block and the
error value is nil so we need to check on it first  
Screen Shot 2023-03-08 at 2 02 53 PM

### CODE REVIEW

**Comment by NSExceptional** [comment]
Passing nil to a function doesn't cause that error. I think `orig` may be nil or corrupted instead

**Comment by ahmedgomaa27** [comment]
@NSExceptional  when i run XCode debugging , i found that error = nil

**Comment by NSExceptional** [comment]
Yes but that won't cause a crash, error is supposed to be nil unless there is an error

**Comment by ryanolsonk** [comment]
I've seen this one. The completion is optional so `orig` can (validly) be nil. We should just guard against that.

**Comment by ahmedgomaa27** [comment]
@NSExceptional  @ryanolsonk  I updated the code now please check

**Comment by ryanolsonk** [comment]
Looks good to me, @NSExceptional ?

**Comment by NSExceptional** [comment]
Thanks!!

**Comment by ahmedgomaa27** [comment]
@NSExceptional  will be a new version for this fix? as i need to upgrade current version

**Pull request merged**
