### PR TITLE
SPM support with binaryTarget xcFramework

### PR DESCRIPTION
**Pull request by apps4everyone**
SPM with binaryTarget xcFramework (build with fastlane from latest release)

Ticket:
https://github.com/FLEXTool/FLEX/issues/303

Package.swift:
```swift
// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "FLEX",
    platforms: [.iOS(.v13)],
    products: [
        .library(
            name: "FLEX",
            targets: ["FLEX"]
        )
    ],
    targets: [
        .binaryTarget(name: "FLEX", path: "build/FLEX.xcframework")
    ]
)
```

with PR https://github.com/FLEXTool/FLEX/pull/551
you can easy generate and update the xcFramework with:
`bundle exec fastlane exportXCFramework`

### CODE REVIEW

**Comment by NSExceptional** [comment]
There's no way that little file is going to compile FLEX correctly 😅 Did you look at the other PR? There are already one or two PRs for this, and we have blockers

**Comment by NSExceptional** [comment]
Sorry, I read these in reverse order! You commented on the other PR.

I have not used fastlane, can you tell me what role it plays here?

**Comment by apps4everyone** [comment]
maybe with next patch? thx

**Comment by apps4everyone** [comment]
@NSExceptional with bundle exec fastlane exportXCFramework you can generate the xcframework into the right directory on every release. Then we can reuse this with SPM and binary target. When this is ok I will look into a next PR to generate with an github action automatically.

**Comment by apps4everyone** [comment]
@NSExceptional did you had time?

**Pull request closed without merging**
