### PR TITLE
fix public header warnings & install path for xcframework compatible with SPM

### PR DESCRIPTION
**Pull request by canius**
- change wrong public headers to private to fix warning using xcframework
- set install path as default

these changes will make FLEX packaged to xcframework better.

### CODE REVIEW

**Comment by NSExceptional** [comment]
Have you tested this with Cocoapods? (You can test your fork by specifying a git URL in your Podfile)

**Comment by canius** [comment]
> Have you tested this with Cocoapods? (You can test your fork by specifying a git URL in your Podfile)

Yes. I've tried both `pod lib lint` and run in a demo app using dev pods without any problem.

**Comment by canius** [comment]
@NSExceptional any update?

**Comment by NSExceptional** [comment]
Thanks @canius! Sorry, been a little preoccupied lately.

**Comment by Qusic** [comment]
The fix may not be correct or complete.
When integrating with Carthage, I am now seeing:
```
dyld: Library not loaded: /Library/Frameworks/FLEX.framework/FLEX

  Referenced from: /private/var/containers/Bundle/Application/<guid>/<myapp>.app/<myapp>

  Reason: image not found
```

With the default value of `@rpath` being `@executable_path/Frameworks`, library `@rpath/FLEX.framework/FLEX` should be working. But now the install name becomes a fixed absolute path.

**Comment by NSExceptional** [comment]
Can you post your binary? I will look at it to see what it is telling dyld to do

**Comment by Qusic** [comment]
`otool -L MyApp` and `otool -l FLEX` both say the install name is `/Library/Frameworks/FLEX.framework/FLEX` but I expect `@rpath/FLEX.framework/FLEX`

here is a sample project built with `xcodegen` and `carthage` (both can be installed with `brew` if you dont have them):

```
cd Test
carthage update --use-xcframeworks
xcodegen
open Test.xcodeproj
```

I am not sure why but it runs sometimes when running from Xcode with debugger attached. However, launching the test app by tapping homescreen icon on the simulator always crashes with the error in my previous comment.

Since `carthage` just builds frameworks with `xcodebuild`. I presume the issue is on FLEX side instead of the app.

[Test.zip](https://github.com/FLEXTool/FLEX/files/6778288/Test.zip)

**Comment by TheCoordinator** [comment]
Yes can confirm this happening on both Simulator and device. On device surprisingly doesn't even work with debugger attached whereas as @Qusic mentioned it does with simulator.

**Comment by canius** [comment]
> `otool -L MyApp` and `otool -l FLEX` both say the install name is `/Library/Frameworks/FLEX.framework/FLEX` but I expect `@rpath/FLEX.framework/FLEX`
> 
> here is a sample project built with `xcodegen` and `carthage` (both can be installed with `brew` if you dont have them):
> 
> ```
> cd Test
> carthage update --use-xcframeworks
> xcodegen
> open Test.xcodeproj
> ```
> 
> I am not sure why but it runs sometimes when running from Xcode with debugger attached. However, launching the test app by tapping homescreen icon on the simulator always crashes with the error in my previous comment.
> 
> Since `carthage` just builds frameworks with `xcodebuild`. I presume the issue is on FLEX side instead of the app.
> 
> [Test.zip](https://github.com/FLEXTool/FLEX/files/6778288/Test.zip)

Hi Qusic, could you have a try again with: github "canius/FLEX" "master"
I guest I found the root cause but my carthage doesn't work.

**Comment by Qusic** [comment]
> 

it doesnt build for me.

```
$ carthage update --use-xcframeworks
*** Fetching FLEX
*** Checking out FLEX at "c485e9f19ce3d409e1bc90bef4768765575839a8"
*** xcodebuild output can be found in /var/folders/xh/9xydkfc51g5__lk8wrgh7cf80000gn/T/carthage-xcodebuild.mZIa77.log
*** Building scheme "FLEX" in FLEX.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/banl/Downloads/Test/Carthage/Checkouts/FLEX/FLEX.xcodeproj -scheme FLEX -configuration Release -derivedDataPath /Users/banl/Library/Caches/org.carthage.CarthageKit/DerivedData/13.3.1_13E500a/FLEX/c485e9f19ce3d409e1bc90bef4768765575839a8 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/xh/9xydkfc51g5__lk8wrgh7cf80000gn/T/FLEX SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/banl/Downloads/Test/Carthage/Checkouts/FLEX)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/xh/9xydkfc51g5__lk8wrgh7cf80000gn/T/carthage-xcodebuild.mZIa77.log
```


The interesting part in `/var/folders/xh/9xydkfc51g5__lk8wrgh7cf80000gn/T/carthage-xcodebuild.mZIa77.log`
```
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_FLEXFirebaseTransaction", referenced from:
      objc-class-ref in FLEXNetworkRecorder.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by canius** [comment]
> Update project.pbxproj to fix crash on launch. #547

The compile error fixed. Please try again. Also the PR is created: https://github.com/FLEXTool/FLEX/pull/597

**Comment by Qusic** [comment]
> > Update project.pbxproj to fix crash on launch. #547
> 
> The compile error fixed. Please try again. Also the PR is created: #597

checked the build with otool and install name looks good!

**Pull request merged**
