### PR TITLE
Add macro to optionally disable FLEX loading at runtime

### PR DESCRIPTION
**Pull request by chrisczupak**
Adding the ability to disable FLEX from loading at runtime by adding the `DISABLE_FLEX_RUNTIME_LOAD` macro in project settings. 

This allows you to make runtime changes without conflicting with FLEX, and also aligns with a recent request that was made for this behavior: https://github.com/FLEXTool/FLEX/issues/470.

### CODE REVIEW

**Comment by matrush** [comment]
@NSExceptional This looks to me, how do you think about this approach vs the one mentioned in #470 for using `NSUserDefaults`?

**Comment by NSExceptional** [comment]
I'm sort of thinking we should accept both! Why not, right?

I'm going to take a deeper look at this this weekend. Not ready to merge it yet

**Comment by NSExceptional** [comment]
I've reviewed the PR (and merged it with some changes I've made yesterday so that it is up to date with `master`) and this is actually not what we need in #470. I thought this was going to add a macro to check for a _runtime_ flag but all this does is determine at compile-time whether the constructors will run or not.

@chrisczupak, would you be okay with a dynamic solution like using an environment variable or an `NSUserDefaults` key? If so, I can close this and I will add that myself. If you need a compile-time macro though, let me know!

**Review by NSExceptional — COMMENTED** [review]
I've reviewed the PR (and merged it with some changes I've made yesterday so that it is up to date with `master`) and this is actually not what we need in #470. I thought this was going to add a macro to check for a _runtime_ flag but all this does is determine at compile-time whether the constructors will run or not.

@chrisczupak, would you be okay with a dynamic solution like using an environment variable or an `NSUserDefaults` key? If so, I can close this and I will add that myself. If you need a compile-time macro though, let me know!

**Comment by chrisczupak** [comment]
Hi, @NSExceptional! Sorry for the delay. I saw the change to [Add FLEX_EXIT_IF_NO_CTORS](Add FLEX_EXIT_IF_NO_CTORS) which looks good. However, I'd still like a compile time macro, so if we can move ahead with this PR as well that would be fantastic! Thank you!

**Comment by NSExceptional** [comment]
Okay! The way I've set it up we won't be using this PR though, so no need to keep pushing commits :P

I did force push your branch to get it up to date with master btw

**Comment by chrisczupak** [comment]
haha ok, thanks for the heads up!

**Comment by NSExceptional** [comment]
Yeah 😆

**Comment by NSExceptional** [comment]
Use `FLEX_DISABLE_CTORS` as of `4.2.0`

**Pull request closed without merging**
