### PR TITLE
Xcode 14 - Warnings related to iOS 11 support (Swift Package Manager)

### PR DESCRIPTION
**Pull request by kikeenrique**
Hi,
I would like to contribute fixing a recent warning.

The new Xcode 14 uses iOS SDK 11.0 as base, and compiling in this Xcode shows a warning.
Handle this restriction relying on swift version.

Regards and comments welcomed

### CODE REVIEW

**Comment by NSExceptional** [comment]
Hi, thank you!

How does this compile though? Shouldn't there be a plain `#else` instead of an `#elseif`?

**Comment by kikeenrique** [comment]
I don't think it's needed to provide all _if_ alternatives to be compilable.
In this case, 5.0 is prior to package file swift-tools-version 5.3, which correspond to swift version 5.3. So it won't be possible to compile with a version out of the covered toolchain.

I did tested it in a custom project, I will test it on the example SPM in the repo, just in case.

**Comment by kikeenrique** [comment]
An unexpected problem, example SPM project uses Reflex (I just learned this existed) instead of Flex package.
Also, current example SPM project  doesn't compile, as it points to a local directory 
`repositoryURL = "file:///Users/tanner/Repos/Reflex";`

To check that it was working, in my fork I've updated example SPM project in branch _update-example_ to use a local Flex package, which uses SPM from the local repo (it uses a relative path), instead of resolving to GitHub

**Comment by NSExceptional** [comment]
I guess it's not technically required since it will compile as long as you're using swift 5 at least, but for clarity's sake, can we change the else to just an `#else` and remove the condition?

**Comment by kikeenrique** [comment]
Yes, of course. Tested and pushed.

**Comment by kikeenrique** [comment]
Hi, I've updated branch with latests commits. It's still in good shape.

**Comment by NSExceptional** [comment]
I missed your reply, whoops! Thank you! Merging now

**Pull request merged**
