### PR TITLE
fixup: Fix crash on iOS 16 and above

### PR DESCRIPTION
**Pull request by talka123456**
fix the bug for issue #606

### CODE REVIEW

**Comment by NSExceptional** [comment]
Thank you!

**Comment by Saafo** [comment]
@NSExceptional iOS 16 formal version will be released in a week, will you release a new version this week to prevent from this serious bug?

**Comment by NSExceptional** [comment]
Yes, sorry! I'll let you know when

**Comment by kingnight** [comment]
please release a new version for this problem，thanks

**Comment by Saafo** [comment]
9 Oct now....🫣

**Comment by Neil20170220** [comment]
please release a new version for this problem，thanks

**Comment by didik-maulana** [comment]
Hi, any update on this issue? 😃 
When will a new version be released to solve this crash?

**Comment by didik-gravel** [comment]
Hi, any update?
please release a new version for this fixed-up crash issue, thanks

**Comment by Saafo** [comment]
[5.22.10](https://github.com/FLEXTool/FLEX/releases/tag/5.22.10) had been released.

**Comment by didik-gravel** [comment]
It's worked now 🎉  
thank you @Saafo and team!

**Comment by fabcz** [comment]
@talka123456 @NSExceptional 
`if (!@available(iOS 16.0, *))` will waring that `@available does not guard availability here; use if (@available) instead`, because @available may only be used as condition of an 'if', 'guard' or 'while' statement, so you can fix like that
```
- (UIWindow *)statusWindow {
    if (@available(iOS 16.0, *) {
        return nil;
    } else {
        NSString *statusBarString = [NSString stringWithFormat:@"%@arWindow", @"_statusB"];
        return [UIApplication.sharedApplication valueForKey:statusBarString];
    }
}
```
[ios-available-does-not-guard-availability-here-use-if-available-instead](https://stackoverflow.com/questions/52251973/ios-available-does-not-guard-availability-here-use-if-available-instead)

**Pull request merged**
