### PR TITLE
Make FLEXFileBrowserController public

### PR DESCRIPTION
**Pull request by kolyuchiy**
This allows to add custom menu item to browse application group container or other path of interest.

This is related to #668.

### CODE REVIEW

**Review by NSExceptional — APPROVED** [review]

**Comment by NSExceptional** [comment]
Awesome! Thanks!

**Comment by talka123456** [comment]
This will result  the FLEXFileBrowserSearchOperation.h header file not found, so it needs to be made public as well.

**Comment by talka123456** [comment]
This will result in the FLEXFileBrowserSearchOperation.h header file being not found, so it needs to be made public as well or move the 'FLEXFileBrowserSearchOperation.h' to FLEXFileBrowserController.m

**Comment by turkcankeskin** [comment]
> This will result in the FLEXFileBrowserSearchOperation.h header file being not found, so it needs to be made public as well or move the 'FLEXFileBrowserSearchOperation.h' to FLEXFileBrowserController.m

Hello,

talka123456's comment and pull request seem justified. I get an error in build-for-testing when using the master branch.
`/Users/jenkinsbuild/Library/Developer/Xcode/DerivedData/XXXX/Build/Products/Debug-iphonesimulator/FLEX/FLEX.framework/Headers/FLEXFileBrowserController.h:11:9: error: 'FLEXFileBrowserSearchOperation.h' file not found
#import "FLEXFileBrowserSearchOperation.h"`

**Pull request merged**
