### PR TITLE
Remove unneeded edgesForExtendedLayout setting

### LINKED ISSUE #571: The navigation header is transparent on iOS 15 when viewing a db table.
### Environment
- Platform+version: **iOS 15**
- FLEX version: **4.5.0**

### Bug Report

The navigation header is transparent on iOS 15 when viewing a db table.
Screenshot:

### PR DESCRIPTION
**Pull request by matrush**
Fixes #571.

See the screenshot after fix:

### CODE REVIEW

**Comment by NSExceptional** [comment]
I will merge this without all of the whitespace-only changes; go back one commit and edit the previous commit to discard those changes. Also, do a force-pull or reset to `origin` first because I force-pushed your branch to get rid of the merge commits in your branch's history

Why are you adding whitespace to blank lines? 😅

**Comment by matrush** [comment]
I didn't meant to change the spaces, I think they were added due to some VSCode settings remove extra whitespaces automatically.

I think we should do a batch update to remove all the whitespaces/tabs on empty lines to avoid formatting issue. Maybe time to consider clang-format or Uncrustify to take care of the formatting issue for us :)

If I squash and merge there will be no spacing change right? So maybe I can just do that instead.

**Comment by NSExceptional** [comment]
> I think we should do a batch update to remove all the whitespaces/tabs on empty lines to avoid formatting issue. Maybe time to consider clang-format or Uncrustify to take care of the formatting issue for us :)

Sure, that would be neat. I have no idea how to set up any of that to where it keeps the established style though lol. Help wanted!

> If I squash and merge there will be no spacing change right? So maybe I can just do that instead.

That will just bring the whitespace changes into one singular commit. Do you use Tower or anything for Git? It makes stuff like going back a commit and discarding specific changes really easy. Highly recommend getting a license if you don't have one already, it's a game changer for Git productivity

**Comment by NSExceptional** [comment]
I can fix it if you want but it'll change me to the author, idk if you care about git history attribution lol

**Pull request merged**
